# Form implementation generated from reading ui file '.\zoomplus_ui\zoomplus_settings_names.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from config import ZoomPlusConfig


class UiEditNameWindow(object):
    def __init__(self):
        self.cfg = ZoomPlusConfig()
        self.statusbar = None
        self.menubar = None
        self.lineEdit_9 = None
        self.lineEdit_10 = None
        self.lineEdit_8 = None
        self.lineEdit_7 = None
        self.lineEdit_6 = None
        self.lineEdit_4 = None
        self.lineEdit_5 = None
        self.lineEdit_3 = None
        self.lineEdit_2 = None
        self.lineEdit = None
        self.verticalLayout = None
        self.widget = None
        self.pushButton = None
        self.centralwidget = None
        self.lineEdit_css = "background-color: #22222e; border: 2px solid #f66867; border-radius: 10px;color: white;"

    def setup_ui(self, EditNameWindow):
        EditNameWindow.setObjectName("EditNameWindow")
        EditNameWindow.resize(240, 545)
        EditNameWindow.setMinimumSize(QtCore.QSize(240, 380))
        EditNameWindow.setMaximumSize(QtCore.QSize(240, 1024))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        EditNameWindow.setFont(font)
        EditNameWindow.setStyleSheet("background-color: #22222e; color: white;")
        self.centralwidget = QtWidgets.QWidget(EditNameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 490, 149, 22))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "color: white;\n"
                                      "background-color: #fb5b5d;\n"
                                      "border-radius: 10px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "background-color: #fa4244;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 0, 151, 471))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(self.lineEdit_css)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet(self.lineEdit_css)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet(self.lineEdit_css)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet(self.lineEdit_css)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet(self.lineEdit_css)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet(self.lineEdit_css)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet(self.lineEdit_css)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet(self.lineEdit_css)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout.addWidget(self.lineEdit_8)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet(self.lineEdit_css)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout.addWidget(self.lineEdit_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet(self.lineEdit_css)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout.addWidget(self.lineEdit_9)
        EditNameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditNameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName("menubar")
        EditNameWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditNameWindow)
        self.statusbar.setObjectName("statusbar")
        EditNameWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditNameWindow)

        self.pushButton.clicked.connect(self.change)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(EditNameWindow)

    def change(self):
        self.cfg.set_name_conf(self.lineEdit.text(), 0)
        self.cfg.set_name_conf(self.lineEdit_2.text(), 1)
        self.cfg.set_name_conf(self.lineEdit_3.text(), 2)
        self.cfg.set_name_conf(self.lineEdit_4.text(), 3)
        self.cfg.set_name_conf(self.lineEdit_5.text(), 4)
        self.cfg.set_name_conf(self.lineEdit_6.text(), 5)
        self.cfg.set_name_conf(self.lineEdit_7.text(), 6)
        self.cfg.set_name_conf(self.lineEdit_8.text(), 7)
        self.cfg.set_name_conf(self.lineEdit_9.text(), 8)
        self.cfg.set_name_conf(self.lineEdit_10.text(), 9)

    def retranslateUi(self, EditNameWindow):
        _translate = QtCore.QCoreApplication.translate
        EditNameWindow.setWindowTitle(_translate("EditNameWindow", "Настройка названия конференций"))
        self.pushButton.setText(_translate("EditNameWindow", "Edit"))
        self.lineEdit.setText(_translate("EditNameWindow", self.cfg.get_name_conf(0)))
        self.lineEdit_2.setText(_translate("EditNameWindow", self.cfg.get_name_conf(1)))
        self.lineEdit_3.setText(_translate("EditNameWindow", self.cfg.get_name_conf(2)))
        self.lineEdit_4.setText(_translate("EditNameWindow", self.cfg.get_name_conf(3)))
        self.lineEdit_5.setText(_translate("EditNameWindow", self.cfg.get_name_conf(4)))
        self.lineEdit_6.setText(_translate("EditNameWindow", self.cfg.get_name_conf(5)))
        self.lineEdit_7.setText(_translate("EditNameWindow", self.cfg.get_name_conf(6)))
        self.lineEdit_8.setText(_translate("EditNameWindow", self.cfg.get_name_conf(7)))
        self.lineEdit_9.setText(_translate("EditNameWindow", self.cfg.get_name_conf(8)))
        self.lineEdit_10.setText(_translate("EditNameWindow", self.cfg.get_name_conf(9)))
