# Form implementation generated from reading ui file '.\zoomplus_ui\zoomplus_create_conf.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from config import ZoomPlusConfig


class UiCreateLessonsWindow(object):
    def __init__(self):
        self.cfg = ZoomPlusConfig()
        self.statusbar = None
        self.menubar = None
        self.label_2 = None
        self.label_1 = None
        self.lineEdit_1 = None
        self.pushButton = None
        self.lineEdit = None
        self.centralwidget = None

    def setup_ui(self, CreateLessonsWindow):
        CreateLessonsWindow.setObjectName("CreateLessonsWindow")
        CreateLessonsWindow.setEnabled(True)
        CreateLessonsWindow.resize(240, 320)
        CreateLessonsWindow.setMinimumSize(QtCore.QSize(240, 320))
        CreateLessonsWindow.setMaximumSize(QtCore.QSize(240, 320))
        CreateLessonsWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        CreateLessonsWindow.setFont(font)
        CreateLessonsWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        CreateLessonsWindow.setStyleSheet("background-color: #22222e; color: white;")
        CreateLessonsWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Russia))
        self.centralwidget = QtWidgets.QWidget(CreateLessonsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(50, 80, 140, 20))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setStyleSheet(
            "bachground-color: #22222e;border: 2px solid #f66867;border-radius: 10px;color: white;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 275, 75, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(1, 3))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777208))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "color: white;\n"
                                      "background-color: #fb5b5d;\n"
                                      "border-radius: 11px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "background-color: #fa4244;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(50, 190, 140, 20))
        self.lineEdit_1.setStyleSheet(
            "bachground-color: #22222e;border: 2px solid #f66867;border-radius: 10px;color: white;")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setEnabled(False)
        self.label_1.setGeometry(QtCore.QRect(80, 150, 80, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 190, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        CreateLessonsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateLessonsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName("menubar")
        CreateLessonsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateLessonsWindow)
        self.statusbar.setObjectName("statusbar")
        CreateLessonsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CreateLessonsWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateLessonsWindow)

    def retranslateUi(self, CreateLessonsWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateLessonsWindow.setWindowTitle(_translate("CreateLessonsWindow", "Создать свою конференцию"))
        self.pushButton.setText(_translate("CreateLessonsWindow", "Создать"))
        self.label_1.setText(_translate("CreateLessonsWindow", "Ссылка:"))
        self.label_2.setText(_translate("CreateLessonsWindow", "Название конференции:"))
