# Form implementation generated from reading ui file '.\zoomplus_ui\zoomplus.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from config import ZoomPlusConfig


class UiZoomPlus(object):
    def __init__(self, window_set_name, window_set_url, window_lessons_conf):
        self.window_set_name = window_set_name
        self.window_set_url = window_set_url
        self.window_lessons_conf = window_lessons_conf
        self.cfg = ZoomPlusConfig()
        self.action_4 = None
        self.action_2 = None
        self.action = None
        self.menu = None
        self.menuEdit = None
        self.menubar = None
        self.statusbar = None
        self.pushButton_8 = None
        self.pushButton_9 = None
        self.pushButton_10 = None
        self.pushButton_7 = None
        self.pushButton_6 = None
        self.pushButton_5 = None
        self.pushButton_4 = None
        self.pushButton_3 = None
        self.pushButton_2 = None
        self.pushButton = None
        self.ZoomPlus = None
        self.button_css = "QPushButton {\n" \
                          "color: white;\n" \
                          "background-color: #fb5b5d;\n" \
                          "border-radius: 10px;\n" \
                          "}\n" \
                          "\n" \
                          "QPushButton:pressed {\n" \
                          "background-color: #fa4244;\n" \
                          "}"

    def setup_ui(self, ZoomPlus):
        ZoomPlus.setObjectName("ZoomPlus")
        ZoomPlus.resize(250, 435)
        ZoomPlus.setMinimumSize(QtCore.QSize(250, 435))
        ZoomPlus.setMaximumSize(QtCore.QSize(250, 435))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        ZoomPlus.setFont(font)
        ZoomPlus.setStyleSheet("background-color: #22222e; color: white;")
        self.ZoomPlus = QtWidgets.QWidget(ZoomPlus)
        self.ZoomPlus.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.ZoomPlus.setObjectName("ZoomPlus")
        self.pushButton = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton.setGeometry(QtCore.QRect(40, 10, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(self.button_css)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 50, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(self.button_css)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 90, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(self.button_css)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 130, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(self.button_css)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 170, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(self.button_css)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 210, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(self.button_css)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 250, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet(self.button_css)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 370, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet(self.button_css)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 330, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet(self.button_css)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.ZoomPlus)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 290, 170, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet(self.button_css)
        self.pushButton_8.setObjectName("pushButton_8")
        ZoomPlus.setCentralWidget(self.ZoomPlus)
        self.statusbar = QtWidgets.QStatusBar(ZoomPlus)
        self.statusbar.setObjectName("statusbar")
        ZoomPlus.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(ZoomPlus)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        ZoomPlus.setMenuBar(self.menubar)
        self.action = QtGui.QAction(ZoomPlus)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(ZoomPlus)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtGui.QAction(ZoomPlus)
        self.action_4.setObjectName("action_4")
        self.menuEdit.addAction(self.action)
        self.menuEdit.addAction(self.action_2)
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ZoomPlus)
        self.pushButton.clicked.connect(lambda: self.cfg.open_url_conf(0))  # type: ignore
        self.pushButton_2.clicked.connect(lambda: self.cfg.open_url_conf(1))  # type: ignore
        self.pushButton_3.clicked.connect(lambda: self.cfg.open_url_conf(2))  # type: ignore
        self.pushButton_4.clicked.connect(lambda: self.cfg.open_url_conf(3))  # type: ignore
        self.pushButton_5.clicked.connect(lambda: self.cfg.open_url_conf(4))  # type: ignore
        self.pushButton_6.clicked.connect(lambda: self.cfg.open_url_conf(5))  # type: ignore
        self.pushButton_7.clicked.connect(lambda: self.cfg.open_url_conf(6))  # type: ignore
        self.pushButton_8.clicked.connect(lambda: self.cfg.open_url_conf(7))  # type: ignore
        self.pushButton_9.clicked.connect(lambda: self.cfg.open_url_conf(8))  # type: ignore
        self.pushButton_10.clicked.connect(lambda: self.cfg.open_url_conf(9))  # type: ignore
        self.action.triggered.connect(self.window_set_url.show)  # type: ignore
        self.action_2.triggered.connect(self.window_set_name.show)  # type: ignore
        self.action_4.triggered.connect(self.window_lessons_conf.show)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ZoomPlus)

    def retranslateUi(self, ZoomPlus):
        _translate = QtCore.QCoreApplication.translate
        ZoomPlus.setWindowTitle(_translate("ZoomPlus", "ZoomPlus"))
        self.pushButton.setText(_translate("ZoomPlus", self.cfg.get_name_conf(0)))
        self.pushButton_2.setText(_translate("ZoomPlus", self.cfg.get_name_conf(1)))
        self.pushButton_3.setText(_translate("ZoomPlus", self.cfg.get_name_conf(2)))
        self.pushButton_4.setText(_translate("ZoomPlus", self.cfg.get_name_conf(3)))
        self.pushButton_5.setText(_translate("ZoomPlus", self.cfg.get_name_conf(4)))
        self.pushButton_6.setText(_translate("ZoomPlus", self.cfg.get_name_conf(5)))
        self.pushButton_7.setText(_translate("ZoomPlus", self.cfg.get_name_conf(6)))
        self.pushButton_10.setText(_translate("ZoomPlus", self.cfg.get_name_conf(9)))
        self.pushButton_9.setText(_translate("ZoomPlus", self.cfg.get_name_conf(8)))
        self.pushButton_8.setText(_translate("ZoomPlus", self.cfg.get_name_conf(7)))
        self.menuEdit.setTitle(_translate("ZoomPlus", "Настройки"))
        self.menu.setTitle(_translate("ZoomPlus", "Создать"))
        self.action.setText(_translate("ZoomPlus", "Настроить ссылки"))
        self.action_2.setText(_translate("ZoomPlus", "Настроить названия"))
        self.action_4.setText(_translate("ZoomPlus", "Создать свою конференцию"))
