# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'zoomplus_settings_urls.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class UiMainWindow(object):
    def __init__(self):
        self.label_style = "QLabel {color:white; font: bold; font-family: Comic Sans MS, sans-serif;}"
        self.line_style = "QLineEdit {border-radius: 10px; color: white; background-color: #4CAF50; font-family: " \
                          "Comic Sans MS, sans-serif; font: bold} "
        self.centralwidget = None
        self.label = None
        self.label_2 = None
        self.label_3 = None
        self.label_4 = None
        self.label_5 = None
        self.label_6 = None
        self.label_7 = None
        self.label_8 = None
        self.label_9 = None
        self.label_10 = None
        self.lineEdit = None
        self.lineEdit_2 = None
        self.lineEdit_3 = None
        self.lineEdit_4 = None
        self.lineEdit_5 = None
        self.lineEdit_6 = None
        self.lineEdit_7 = None
        self.lineEdit_8 = None
        self.lineEdit_9 = None
        self.lineEdit_10 = None
        self.menubar = None
        self.statusbar = None

    def setup_ui(self, main_window, action=None):
        main_window.setObjectName("MainWindow")
        main_window.resize(240, 360)
        main_window.setMinimumSize(QtCore.QSize(240, 370))
        main_window.setMaximumSize(QtCore.QSize(240, 370))
        main_window.setStyleSheet("QMainWindow {background-color: #555}")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 75, 15))
        self.label.setStyleSheet(self.label_style)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 80, 15))
        self.label_2.setStyleSheet(self.label_style)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 75, 75, 15))
        self.label_3.setStyleSheet(self.label_style)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 75, 15))
        self.label_4.setStyleSheet(self.label_style)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 145, 83, 15))
        self.label_5.setStyleSheet(self.label_style)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 75, 15))
        self.label_6.setStyleSheet(self.label_style)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 215, 75, 15))
        self.label_7.setStyleSheet(self.label_style)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 75, 15))
        self.label_8.setStyleSheet(self.label_style)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 285, 75, 15))
        self.label_9.setStyleSheet(self.label_style)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 320, 75, 15))
        self.label_10.setStyleSheet(self.label_style)
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 5, 113, 20))
        self.lineEdit.setStyleSheet(self.line_style)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 40, 113, 20))
        self.lineEdit_2.setStyleSheet(self.line_style)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 75, 113, 20))
        self.lineEdit_3.setStyleSheet(self.line_style)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.lineEdit_4.setStyleSheet(self.line_style)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 145, 113, 20))
        self.lineEdit_5.setStyleSheet(self.line_style)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 180, 113, 20))
        self.lineEdit_6.setStyleSheet(self.line_style)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(110, 215, 113, 20))
        self.lineEdit_7.setStyleSheet(self.line_style)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 250, 113, 20))
        self.lineEdit_8.setStyleSheet(self.line_style)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 285, 113, 20))
        self.lineEdit_9.setStyleSheet(self.line_style)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 320, 113, 20))
        self.lineEdit_10.setStyleSheet(self.line_style)
        self.lineEdit_10.setObjectName("lineEdit_10")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window, action=action)

        self.lineEdit.textChanged['QString'].connect(action.set_url_conf_0)  # type: ignore
        self.lineEdit_2.textChanged['QString'].connect(action.set_url_conf_1)  # type: ignore
        self.lineEdit_3.textChanged['QString'].connect(action.set_url_conf_2)  # type: ignore
        self.lineEdit_4.textChanged['QString'].connect(action.set_url_conf_3)  # type: ignore
        self.lineEdit_5.textChanged['QString'].connect(action.set_url_conf_4)  # type: ignore
        self.lineEdit_6.textChanged['QString'].connect(action.set_url_conf_5)  # type: ignore
        self.lineEdit_8.textChanged['QString'].connect(action.set_url_conf_7)  # type: ignore
        self.lineEdit_7.textChanged['QString'].connect(action.set_url_conf_6)  # type: ignore
        self.lineEdit_10.textChanged['QString'].connect(action.set_url_conf_9)  # type: ignore
        self.lineEdit_9.textChanged['QString'].connect(action.set_url_conf_8)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window, action=None):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "Настройка ссылок"))
        self.label.setText(_translate("MainWindow", action.get_name_conf(index_conf=0)))
        self.label_2.setText(_translate("MainWindow", action.get_name_conf(index_conf=1)))
        self.label_3.setText(_translate("MainWindow", action.get_name_conf(index_conf=2)))
        self.label_4.setText(_translate("MainWindow", action.get_name_conf(index_conf=3)))
        self.label_5.setText(_translate("MainWindow", action.get_name_conf(index_conf=4)))
        self.label_6.setText(_translate("MainWindow", action.get_name_conf(index_conf=5)))
        self.label_7.setText(_translate("MainWindow", action.get_name_conf(index_conf=6)))
        self.label_8.setText(_translate("MainWindow", action.get_name_conf(index_conf=7)))
        self.label_9.setText(_translate("MainWindow", action.get_name_conf(index_conf=8)))
        self.label_10.setText(_translate("MainWindow", action.get_name_conf(index_conf=9)))
        self.lineEdit.setText(_translate("MainWindow", action.get_url_conf(index_conf=0)))
        self.lineEdit_2.setText(_translate("MainWindow", action.get_url_conf(index_conf=1)))
        self.lineEdit_3.setText(_translate("MainWindow", action.get_url_conf(index_conf=2)))
        self.lineEdit_4.setText(_translate("MainWindow", action.get_url_conf(index_conf=3)))
        self.lineEdit_5.setText(_translate("MainWindow", action.get_url_conf(index_conf=4)))
        self.lineEdit_6.setText(_translate("MainWindow", action.get_url_conf(index_conf=5)))
        self.lineEdit_7.setText(_translate("MainWindow", action.get_url_conf(index_conf=6)))
        self.lineEdit_8.setText(_translate("MainWindow", action.get_url_conf(index_conf=7)))
        self.lineEdit_9.setText(_translate("MainWindow", action.get_url_conf(index_conf=8)))
        self.lineEdit_10.setText(_translate("MainWindow", action.get_url_conf(index_conf=9)))
