# Form implementation generated from reading ui file '.\zoomplus_ui\zoomplus_settings_urls.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from config import ZoomPlusConfig


class UiEditUrlWindow(object):
    def __init__(self):
        self.cfg = ZoomPlusConfig()
        self.statusbar = None
        self.menubar = None
        self.lineEdit_10 = None
        self.lineEdit_9 = None
        self.lineEdit_8 = None
        self.lineEdit_7 = None
        self.lineEdit_6 = None
        self.lineEdit_5 = None
        self.lineEdit_4 = None
        self.lineEdit_3 = None
        self.lineEdit_2 = None
        self.lineEdit = None
        self.verticalLayout_2 = None
        self.widget1 = None
        self.label_10 = None
        self.label_9 = None
        self.label_8 = None
        self.label_7 = None
        self.label_6 = None
        self.label_5 = None
        self.label_4 = None
        self.label_3 = None
        self.label_2 = None
        self.label = None
        self.verticalLayout = None
        self.widget = None
        self.pushButton = None
        self.centralwidget = None
        self.lineEdit_css = "bachground-color: #22222e;\n" \
                            "border: 2px solid #f66867;\n" \
                            "border-radius: 10px;\n" \
                            "color: white;"

    def setup_ui(self, EditUrlWindow):
        EditUrlWindow.setObjectName("EditUrlWindow")
        EditUrlWindow.resize(260, 405)
        EditUrlWindow.setMinimumSize(QtCore.QSize(260, 405))
        EditUrlWindow.setMaximumSize(QtCore.QSize(260, 405))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        EditUrlWindow.setFont(font)
        EditUrlWindow.setStyleSheet("background-color: #22222e; color: white;")
        self.centralwidget = QtWidgets.QWidget(EditUrlWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 360, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "color: white;\n"
                                      "background-color: #fb5b5d;\n"
                                      "border-radius: 10px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "background-color: #fa4244;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 5, 111, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(130, 0, 121, 341))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(self.lineEdit_css)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet(self.lineEdit_css)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet(self.lineEdit_css)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet(self.lineEdit_css)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet(self.lineEdit_css)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet(self.lineEdit_css)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet(self.lineEdit_css)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_2.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet(self.lineEdit_css)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_2.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet(self.lineEdit_css)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_2.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet(self.lineEdit_css)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_2.addWidget(self.lineEdit_10)
        EditUrlWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditUrlWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 260, 21))
        self.menubar.setObjectName("menubar")
        EditUrlWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditUrlWindow)
        self.statusbar.setObjectName("statusbar")
        EditUrlWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditUrlWindow)

        self.pushButton.clicked.connect(self.change)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(EditUrlWindow)

    def change(self):
        self.cfg.set_url_conf(self.lineEdit.text(), 0)
        self.cfg.set_url_conf(self.lineEdit_2.text(), 1)
        self.cfg.set_url_conf(self.lineEdit_3.text(), 2)
        self.cfg.set_url_conf(self.lineEdit_4.text(), 3)
        self.cfg.set_url_conf(self.lineEdit_5.text(), 4)
        self.cfg.set_url_conf(self.lineEdit_6.text(), 5)
        self.cfg.set_url_conf(self.lineEdit_7.text(), 6)
        self.cfg.set_url_conf(self.lineEdit_8.text(), 7)
        self.cfg.set_url_conf(self.lineEdit_9.text(), 8)
        self.cfg.set_url_conf(self.lineEdit_10.text(), 9)

    def retranslateUi(self, EditUrlWindow):
        _translate = QtCore.QCoreApplication.translate
        EditUrlWindow.setWindowTitle(_translate("EditUrlWindow", "Настройка ссылок конференции"))
        self.pushButton.setText(_translate("EditUrlWindow", "Edit"))
        self.label.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(0)))
        self.label_2.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(1)))
        self.label_3.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(2)))
        self.label_4.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(3)))
        self.label_5.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(4)))
        self.label_6.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(5)))
        self.label_7.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(6)))
        self.label_8.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(7)))
        self.label_9.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(8)))
        self.label_10.setText(_translate("EditUrlWindow", self.cfg.get_name_conf(9)))
        self.lineEdit.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(0)))
        self.lineEdit_2.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(1)))
        self.lineEdit_3.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(2)))
        self.lineEdit_4.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(3)))
        self.lineEdit_5.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(4)))
        self.lineEdit_6.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(5)))
        self.lineEdit_7.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(6)))
        self.lineEdit_8.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(7)))
        self.lineEdit_9.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(8)))
        self.lineEdit_10.setText(_translate("EditUrlWindow", self.cfg.get_url_conf(9)))
