# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'zoomplus.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

_name_app = "ZoomPlus"


class UiZoomPlus(object):
    def __init__(self, window_set_name, window_set_url, window_lessons_conf):
        self.window_set_name = window_set_name
        self.window_set_url = window_set_url
        self.window_lessons_conf = window_lessons_conf
        self.lesson_conf = None
        self.pushButton = None
        self.pushButton_3 = None
        self.pushButton_4 = None
        self.pushButton_5 = None
        self.statusbar = None
        self.menuEdit = None
        self.menu = None
        self.settings_urls_conf = None
        self.settings_name_conf = None
        self.create_lesson_conf = None
        self.ZoomPlus_2 = None
        self.pushButton_2 = None
        self.pushButton_6 = None
        self.pushButton_7 = None
        self.pushButton_10 = None
        self.pushButton_8 = None
        self.pushButton_9 = None
        self.menubar = None
        self.button_style = "QPushButton {border-radius: 10px; color: #fff;text-align: center;font-size: 12px;font: " \
                            "bold;text-align: center;font-family: \'Comic Sans MS\', sans-serif;} \n" \
                            "QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, " \
                            "stop:0.210227 rgba(0, 255, 162, 100), stop:1 rgba(255, 255, 255, 100));} "

    def setup_ui(self, zoom_plus, action=None):
        zoom_plus.setObjectName("ZoomPlus")
        zoom_plus.resize(250, 435)
        zoom_plus.setMinimumSize(QtCore.QSize(250, 435))
        zoom_plus.setMaximumSize(QtCore.QSize(250, 435))
        zoom_plus.setStyleSheet(
            "QMainWindow {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.210227 rgba("
            "253,187,45,1), stop:1 rgba(195,34,34,1));}")
        self.ZoomPlus_2 = QtWidgets.QWidget(zoom_plus)
        self.ZoomPlus_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.ZoomPlus_2.setObjectName("ZoomPlus_2")
        self.pushButton = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 10, 100, 20))
        self.pushButton.setStyleSheet(self.button_style)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 50, 100, 20))
        self.pushButton_2.setStyleSheet(self.button_style)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 90, 100, 20))
        self.pushButton_3.setStyleSheet(self.button_style)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 130, 100, 20))
        self.pushButton_4.setStyleSheet(self.button_style)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 170, 100, 20))
        self.pushButton_5.setStyleSheet(self.button_style)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 210, 100, 20))
        self.pushButton_6.setStyleSheet(self.button_style)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 250, 100, 20))
        self.pushButton_7.setStyleSheet(self.button_style)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 370, 100, 20))
        self.pushButton_8.setStyleSheet(self.button_style)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_9.setGeometry(QtCore.QRect(80, 330, 100, 20))
        self.pushButton_9.setStyleSheet(self.button_style)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.ZoomPlus_2)
        self.pushButton_10.setGeometry(QtCore.QRect(80, 290, 100, 20))
        self.pushButton_10.setStyleSheet(self.button_style)
        self.pushButton_10.setObjectName("pushButton_10")
        zoom_plus.setCentralWidget(self.ZoomPlus_2)
        self.statusbar = QtWidgets.QStatusBar(zoom_plus)
        self.statusbar.setObjectName("statusbar")
        zoom_plus.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(zoom_plus)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        zoom_plus.setMenuBar(self.menubar)
        self.settings_urls_conf = QtGui.QAction(self.window_set_url)
        self.settings_urls_conf.setObjectName("settings_urls")
        self.settings_name_conf = QtGui.QAction(self.window_set_name)
        self.settings_name_conf.setObjectName("settings_name_conf")
        self.create_lesson_conf = QtGui.QAction(self.lesson_conf)
        self.create_lesson_conf.setObjectName("create_lesson_conf")
        self.menuEdit.addAction(self.settings_urls_conf)
        self.menuEdit.addAction(self.settings_name_conf)
        self.menu.addAction(self.create_lesson_conf)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslate_ui(zoom_plus, action=action)
        self.pushButton.clicked.connect(lambda: action.open_url_conf(index_conf=0))  # type: ignore
        self.pushButton_2.clicked.connect(lambda: action.open_url_conf(index_conf=1))  # type: ignore
        self.pushButton_3.clicked.connect(lambda: action.open_url_conf(index_conf=2))  # type: ignore
        self.pushButton_4.clicked.connect(lambda: action.open_url_conf(index_conf=3))  # type: ignore
        self.pushButton_5.clicked.connect(lambda: action.open_url_conf(index_conf=4))  # type: ignore
        self.pushButton_6.clicked.connect(lambda: action.open_url_conf(index_conf=5))  # type: ignore
        self.pushButton_7.clicked.connect(lambda: action.open_url_conf(index_conf=6))  # type: ignore
        self.pushButton_10.clicked.connect(lambda: action.open_url_conf(index_conf=9))  # type: ignore
        self.pushButton_9.clicked.connect(lambda: action.open_url_conf(index_conf=8))  # type: ignore
        self.pushButton_8.clicked.connect(lambda: action.open_url_conf(index_conf=7))  # type: ignore
        self.settings_name_conf.triggered.connect(self.window_set_name.show)  # type: ignore
        self.settings_urls_conf.triggered.connect(self.window_set_url.show)  # type: ignore
        self.create_lesson_conf.triggered.connect(self.window_lessons_conf.show)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(zoom_plus)

    def retranslate_ui(self, zoom_plus, action=None):
        _translate = QtCore.QCoreApplication.translate
        zoom_plus.setWindowTitle(_translate("ZoomPlus", _name_app))
        self.pushButton.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=0)))
        self.pushButton_2.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=1)))
        self.pushButton_3.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=2)))
        self.pushButton_4.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=3)))
        self.pushButton_5.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=4)))
        self.pushButton_6.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=5)))
        self.pushButton_7.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=6)))
        self.pushButton_8.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=7)))
        self.pushButton_9.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=8)))
        self.pushButton_10.setText(_translate("ZoomPlus", action.get_name_conf(index_conf=9)))
        self.menuEdit.setTitle(_translate("ZoomPlus", "Настройки"))
        self.menu.setTitle(_translate("ZoomPlus", "Создать"))
        self.settings_urls_conf.setText(_translate("ZoomPlus", "Настроить ссылки"))
        self.settings_name_conf.setText(_translate("ZoomPlus", "Настроить названия предметов"))
        self.create_lesson_conf.setText(_translate("ZoomPlus", "Создать свой урок"))
