# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'zoomplus_create_conf.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiCreateLessonsWindow(object):
    def __init__(self):
        self.statusbar = None
        self.menubar = None
        self.label_2 = None
        self.label_1 = None
        self.lineEdit_1 = None
        self.pushButton = None
        self.lineEdit = None
        self.central_widget = None

    def setup_ui(self, main_window, action=None):
        main_window.setObjectName("main_window")
        main_window.setEnabled(True)
        main_window.resize(240, 320)
        main_window.setMinimumSize(QtCore.QSize(240, 320))
        main_window.setMaximumSize(QtCore.QSize(240, 320))
        main_window.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        main_window.setFont(font)
        main_window.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        main_window.setStyleSheet("QMainWindow {background-color: #555}")
        main_window.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Russia))
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.lineEdit = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(60, 60, 110, 20))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setStyleSheet("QLineEdit {border-radius: 10px; color: white; background-color: #4CAF50; "
                                    "font-family: Comic Sans MS, sans-serif; font: bold}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.central_widget)
        self.pushButton.setGeometry(QtCore.QRect(80, 275, 75, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(1, 3))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777208))
        self.pushButton.setStyleSheet("QPushButton {border-radius: 10px; color: #fff;text-align: center;font-size: "
                                      "12px;font: bold;text-align: center;font-family: \'Comic Sans MS\', sans-serif "
                                      ";background-color: #4CAF50} \n "
                                      "QPushButton:hover{background-color: #fff; color: #000}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_1.setGeometry(QtCore.QRect(60, 150, 113, 20))
        self.lineEdit_1.setStyleSheet("QLineEdit {border-radius: 10px; color: white; background-color: #4CAF50; "
                                      "font-family: Comic Sans MS, sans-serif; font: bold}")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_1 = QtWidgets.QLabel(self.central_widget)
        self.label_1.setEnabled(False)
        self.label_1.setGeometry(QtCore.QRect(90, 125, 45, 10))
        self.label_1.setStyleSheet("QLabel {color: white; font-family: Comic Sans MS, sans-serif; font: bold}")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(65, 36, 105, 10))
        self.label_2.setStyleSheet("QLabel {color: white; font-family: Comic Sans MS, sans-serif; font: bold}")
        self.label_2.setObjectName("label_2")
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window)
        name = self.lineEdit.textChanged['QString'].connect(action.get_name_lesson)  # type: ignore
        url = self.lineEdit_1.textChanged['QString'].connect(action.get_url_lesson)  # type: ignore
        self.pushButton.clicked.connect(lambda: action.create_lesson(name=name, url=url))  # type: ignore
        # self.pushButton.clicked.connect(lambda: action.create_lesson(name=self.lineEdit.textChanged['QString'].connect(action.get_name_lesson), url=self.lineEdit_1.textChanged['QString'].connect(action.get_url_lesson)))  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Создать свой урок"))
        self.pushButton.setText(_translate("main_window", "Создать"))
        self.label_1.setText(_translate("main_window", "Ссылка:"))
        self.label_2.setText(_translate("main_window", "Название предмета:"))
