# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'zoomplus_settings_names.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiEditNameWindow(object):
    def __init__(self):
        self.central_widget = None
        self.lineEdit = None
        self.lineEdit_2 = None
        self.lineEdit_3 = None
        self.lineEdit_4 = None
        self.lineEdit_5 = None
        self.lineEdit_6 = None
        self.lineEdit_7 = None
        self.lineEdit_8 = None
        self.lineEdit_9 = None
        self.lineEdit_10 = None
        self.menubar = None
        self.statusbar = None
        self.line_style = "QLineEdit {border-radius: 10px; color: white; background-color: #4CAF50; font-family: " \
                          "Comic Sans MS, sans-serif; font: bold}"
        self.list_lineEdit = []

    def setup_ui(self, edit_name_window, action=None):
        edit_name_window.setObjectName("edit_name_window")
        edit_name_window.resize(240, 320)
        edit_name_window.setMinimumSize(QtCore.QSize(240, 330))
        edit_name_window.setMaximumSize(QtCore.QSize(240, 330))
        edit_name_window.setStyleSheet("QMainWindow {background-color: #555;}")
        self.central_widget = QtWidgets.QWidget(edit_name_window)
        self.central_widget.setObjectName("central_widget")
        self.lineEdit = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit.setGeometry(QtCore.QRect(67, 10, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS, sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(self.line_style)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(67, 40, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet(self.line_style)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(67, 70, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet(self.line_style)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(67, 100, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet(self.line_style)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(67, 130, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet(self.line_style)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(67, 160, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet(self.line_style)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(67, 220, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet(self.line_style)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_8.setGeometry(QtCore.QRect(67, 190, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet(self.line_style)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(67, 280, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet(self.line_style)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_10.setGeometry(QtCore.QRect(67, 250, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,sans-serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet(self.line_style)
        self.lineEdit_10.setObjectName("lineEdit_10")
        edit_name_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(edit_name_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName("menubar")
        edit_name_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(edit_name_window)
        self.statusbar.setObjectName("statusbar")
        edit_name_window.setStatusBar(self.statusbar)

        self.retranslate_ui(edit_name_window, action=action)
        self.lineEdit.textChanged['QString'].connect(action.set_name_conf_0)  # type: ignore
        self.lineEdit_2.textChanged['QString'].connect(action.set_name_conf_1)  # type: ignore
        self.lineEdit_3.textChanged['QString'].connect(action.set_name_conf_2)  # type: ignore
        self.lineEdit_4.textChanged['QString'].connect(action.set_name_conf_3)  # type: ignore
        self.lineEdit_5.textChanged['QString'].connect(action.set_name_conf_4)  # type: ignore
        self.lineEdit_6.textChanged['QString'].connect(action.set_name_conf_5)  # type: ignore
        self.lineEdit_8.textChanged['QString'].connect(action.set_name_conf_7)  # type: ignore
        self.lineEdit_7.textChanged['QString'].connect(action.set_name_conf_6)  # type: ignore
        self.lineEdit_10.textChanged['QString'].connect(action.set_name_conf_9)  # type: ignore
        self.lineEdit_9.textChanged['QString'].connect(action.set_name_conf_8)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(edit_name_window)

    def retranslate_ui(self, edit_name_window, action=None):
        _translate = QtCore.QCoreApplication.translate
        edit_name_window.setWindowTitle(_translate("edit_name_window", "Настройка названий предметов"))
        self.lineEdit.setText(_translate("edit_name_window", action.get_name_conf(index_conf=0)))
        self.lineEdit_2.setText(_translate("edit_name_window", action.get_name_conf(index_conf=1)))
        self.lineEdit_3.setText(_translate("edit_name_window", action.get_name_conf(index_conf=2)))
        self.lineEdit_4.setText(_translate("edit_name_window", action.get_name_conf(index_conf=3)))
        self.lineEdit_5.setText(_translate("edit_name_window", action.get_name_conf(index_conf=4)))
        self.lineEdit_6.setText(_translate("edit_name_window", action.get_name_conf(index_conf=5)))
        self.lineEdit_7.setText(_translate("edit_name_window", action.get_name_conf(index_conf=6)))
        self.lineEdit_8.setText(_translate("edit_name_window", action.get_name_conf(index_conf=7)))
        self.lineEdit_9.setText(_translate("edit_name_window", action.get_name_conf(index_conf=8)))
        self.lineEdit_10.setText(_translate("edit_name_window", action.get_name_conf(index_conf=9)))
